#BNF+EM V1.1;
!grammar COMMAND;

!import <BACK>;
!import <EXIT>;
!import <HELP>;
!import <LINE_NUMBER14>;
!import <NEXT_PAGE>;
!import <PREVIOUS_PAGE>;
!import <FM_LIST>;
!import <AM_LIST>;
!import <DMB_LIST>;

!start <COMMAND>;

<COMMAND>:
<PART>;

<PART>:
<BACK>|
<EXIT>|
<HELP>|
<LINE_NUMBER14>|
<NEXT_PAGE>|
<PREVIOUS_PAGE>|
<FM_LIST>|
<AM_LIST>|
<DMB_LIST>;
