#BNF+EM V1.1;
!grammar COMMAND;

!import <BACK>;
!import <EXIT>;
!import <PHONE_HELP>;
!import <RADIO_HELP>;
!import <MEDIA_HELP>;
!import <DMB_HELP>;
!import <NAVIGATION_HELP>;

!start <COMMAND>;

<COMMAND>:
<PART>;

<PART>:
<BACK>|
<EXIT>|
<PHONE_HELP>|
<RADIO_HELP>|
<MEDIA_HELP>|
<DMB_HELP>|
<NAVIGATION_HELP>;
