#BNF+EM V1.1;
!grammar COMMAND;

!import <CD_PLAY_TRACK>;
!import <HELP>;
!import <EXIT>;
!import <PHONE_CALL>;
//!import <PHONE_DIAL_NUMBER>;
//!import <VAD_NUMBER>;
!import <PHONE_CALL_HISTORY>;
!import <PHONE_REDIAL>;
!import <RADIO>;
!import <RADIO_STATION>;
!import <FM>;
!import <FM_NUMBER>;
!import <FM_FREQUENCY>;
!import <AM>;
!import <AM_FREQUENCY>;
!import <PRESET_NUMBER110>;
!import <PRESET_NUMBER112>;
!import <PRESET_NUMBER140>;
!import <IPOD>;
!import <BT_AUDIO>;
!import <AUX>;
!import <MUSIC>;
!import <MY_MUSIC>;
!import <USB>;
!import <PLAY>;
!import <PAUSE>;
!import <SHUFFLE>;
!import <SHUFFLE_OFF>;
!import <REPEAT>;
!import <REPEAT_OFF>;
!import <VIDEO>;
!import <IMAGE>;
!import <DESTINATION_SEARCH>;
!import <NEAR_POI>;
!import <NEAR_DESTINATION_POI>;
!import <SHOW_MAP>;
!import <PREVIOUS_POINT>;
!import <PREVIOUS_DESTINATION>;
!import <PREVIOUS_SEARCH>;
!import <PREVIOUS_START>;
!import <TRAFFIC_INFO>;
!import <GO_HOME>;
!import <GO_TO_OFFICE>;
!import <TURN_GUIDANCE_ON>;
!import <TURN_GUIDANCE_OFF>;
!import <CANCEL_ROUTE>;
!import <DESTINATION_INFO>;
!import <ROUTE_OPTION>;
!import <FIND_FASTER_TIME>;
!import <FIND_SHORTER_DISTANCE>;
!import <SHOW_ROUTE>;
!import <DMB>;
!import <DMB_STATION>;
!import <STATION_LIST>;
!import <RADIO_AST>;
!import <DMB_AST>;


!start <COMMAND>;

<COMMAND>:
<PART>;

<PART>:
<CD_PLAY_TRACK>|
<HELP>|
<EXIT>|
<PHONE_CALL>|
//<PHONE_DIAL_NUMBER>|
//<VAD_NUMBER>|
<PHONE_CALL_HISTORY>|
<PHONE_REDIAL>|
<RADIO>|
<RADIO_STATION>|
<FM>|
<FM_NUMBER>|
<FM_FREQUENCY>|
<AM>|
<AM_FREQUENCY>|
<PRESET_NUMBER110>|
<PRESET_NUMBER112>|
<PRESET_NUMBER140>|
<IPOD>|
<BT_AUDIO>|
<AUX>|
<MUSIC>|
<MY_MUSIC>|
<USB>|
<PLAY>|
<PAUSE>|
<SHUFFLE>|
<SHUFFLE_OFF>|
<REPEAT>|
<REPEAT_OFF>|
<VIDEO>|
<IMAGE>|
<DESTINATION_SEARCH>|
<NEAR_POI>|
<NEAR_DESTINATION_POI>|
<SHOW_MAP>|
<PREVIOUS_POINT>|
<PREVIOUS_DESTINATION>|
<PREVIOUS_SEARCH>|
<PREVIOUS_START>|
<TRAFFIC_INFO>|
<GO_HOME>|
<GO_TO_OFFICE>|
<TURN_GUIDANCE_ON>|
<TURN_GUIDANCE_OFF>|
<CANCEL_ROUTE>|
<DESTINATION_INFO>|
<ROUTE_OPTION>|
<FIND_FASTER_TIME>|
<FIND_SHORTER_DISTANCE>|
<SHOW_ROUTE>|
<DMB>|
<DMB_STATION>|
<STATION_LIST>|
<RADIO_AST>|
<DMB_AST>;

