#BNF+EM V1.1;
!grammar COMMAND;

!import <BACK>;
!import <EXIT>;
!import <NEXT_PAGE>;
!import <PREVIOUS_PAGE>;
!import <RADIO>;
!import <RADIO_STATION>;
!import <FM>;
!import <FM_NUMBER>;
!import <FM_FREQUENCY>;
!import <AM>;
!import <AM_FREQUENCY>;
!import <RADIO_AST>;
!import <DMB_AST>;
!import <PRESET_NUMBER110>;
!import <PRESET_NUMBER112>;
!import <PRESET_NUMBER140>;

!start <COMMAND>;

<COMMAND>:
<PART>;

<PART>:
<BACK>|
<EXIT>|
<NEXT_PAGE>|
<PREVIOUS_PAGE>|
<RADIO>|
<RADIO_STATION>|
<FM>|
<FM_NUMBER>|
<FM_FREQUENCY>|
<AM>|
<AM_FREQUENCY>|
<RADIO_AST>|
<DMB_AST>|
<PRESET_NUMBER110>|
<PRESET_NUMBER112>|
<PRESET_NUMBER140>;
