#BNF+EM V1.1;
!grammar COMMAND;
!import <BACK>;
!import <EXIT>;
!import <DESTINATION_SEARCH>;
!import <NEAR_POI>;
!import <NEAR_DESTINATION_POI>;
!import <SHOW_MAP>;
!import <PREVIOUS_POINT>;
!import <PREVIOUS_DESTINATION>;
!import <PREVIOUS_SEARCH>;
!import <PREVIOUS_START>;
!import <TRAFFIC_INFO>;
!import <GO_HOME>;
!import <GO_TO_OFFICE>;
!import <TURN_GUIDANCE_ON>;
!import <TURN_GUIDANCE_OFF>;
!import <CANCEL_ROUTE>;
!import <DESTINATION_INFO>;
!import <ROUTE_OPTION>;
!import <FIND_FASTER_TIME>;
!import <FIND_SHORTER_DISTANCE>;
!import <SHOW_ROUTE>;
!import <NEXT_PAGE>;
!import <PREVIOUS_PAGE>;

!start <COMMAND>;

<COMMAND>:

<PART>;

<PART>:

<BACK>|
<EXIT>|
<DESTINATION_SEARCH>|
<NEAR_POI>|
<NEAR_DESTINATION_POI>|
<SHOW_MAP>|
<PREVIOUS_POINT>|
<PREVIOUS_DESTINATION>|
<PREVIOUS_SEARCH>|
<PREVIOUS_START>|
<TRAFFIC_INFO>|
<GO_HOME>|
<GO_TO_OFFICE>|
<TURN_GUIDANCE_ON>|
<TURN_GUIDANCE_OFF>|
<CANCEL_ROUTE>|
<DESTINATION_INFO>|
<ROUTE_OPTION>|
<FIND_FASTER_TIME>|
<FIND_SHORTER_DISTANCE>|
<SHOW_ROUTE>|
<NEXT_PAGE>|
<PREVIOUS_PAGE>;


