#BNF+EM V1.1;
!grammar COMMAND;
!import <BACK>;
!import <EXIT>;
!import <HELP>;
!import <NAVI_GANGWONDO>;
!import <NAVI_GYEONGGIDO>;
!import <NAVI_GYEONGSANGNAMDO>;
!import <NAVI_GYEONGSANGBUKDO>;
!import <NAVI_GWANGJU>;
!import <NAVI_DAEGU>;
!import <NAVI_DAEJEON>;
!import <NAVI_BUSAN>;
!import <NAVI_SEOUL>;
!import <NAVI_SEJONG>;
!import <NAVI_ULSAN>;
!import <NAVI_INCHEON>;
!import <NAVI_JEOLLANAMDO>;
!import <NAVI_JEOLLABUKDO>;
!import <NAVI_JEJUDO>;
!import <NAVI_CHUNGCHUNGNAMDO>;
!import <NAVI_CHUNGCHUNGBUKDO>;

!start <COMMAND>;

<COMMAND>:

<PART>;

<PART>:

<BACK>|
<EXIT>|
<HELP>|
<NAVI_GANGWONDO>|
<NAVI_GYEONGGIDO>|
<NAVI_GYEONGSANGNAMDO>|
<NAVI_GYEONGSANGBUKDO>|
<NAVI_GWANGJU>|
<NAVI_DAEGU>|
<NAVI_DAEJEON>|
<NAVI_BUSAN>|
<NAVI_SEOUL>|
<NAVI_SEJONG>|
<NAVI_ULSAN>|
<NAVI_INCHEON>|
<NAVI_JEOLLANAMDO>|
<NAVI_JEOLLABUKDO>|
<NAVI_JEJUDO>|
<NAVI_CHUNGCHUNGNAMDO>|
<NAVI_CHUNGCHUNGBUKDO>;

