#BNF+EM V1.1;
!grammar COMMAND;

!import <BACK>;
!import <EXIT>;
!import <HELP>;
!import <NAVI_LINE_NUMBER14>;
!import <NEXT_PAGE>;
!import <PREVIOUS_PAGE>;

!start <COMMAND>;


<COMMAND>:

<PART>;

<PART>:

<BACK>|
<EXIT>|
<HELP>|
<NAVI_LINE_NUMBER14>|
<NEXT_PAGE>|
<PREVIOUS_PAGE>;


