#BNF+EM V1.1;
!grammar COMMAND;
!import <NEAR_POI_CATEGORY>;
!import <NEAR_DESTINATION_POI_CATEGORY>;


!start <COMMAND>;

<COMMAND>:

<PART>;

<PART>:

<NEAR_POI_CATEGORY>|
<NEAR_DESTINATION_POI_CATEGORY>;

