#BNF+EM V1.1;
!grammar COMMAND;
!import <BACK>;
!import <EXIT>;
!import <HELP>;
!import <CATEGORY_NAME_BIG>;
!import <CATEGORY_NAME_MID>;
!import <NEXT_PAGE>;
!import <PREVIOUS_PAGE>;


!start <COMMAND>;

<COMMAND>:

<PART>;

<PART>:

<BACK>|
<EXIT>|
<HELP>|
<CATEGORY_NAME_BIG>|
<CATEGORY_NAME_MID>|
<NEXT_PAGE>|
<PREVIOUS_PAGE>;

